<?php

return [
    'starter' => [
        'name' => 'Starter',
        'price_monthly' => 99,
        'price_yearly' => 79,
        'minutes' => 500,
        'bots' => 1,
        'channels' => 2,
        'max_products' => 500,
        'overage_per_minute' => 0.15,
        'allowed_channels' => ['voice', 'web_chatbot'],
        'features' => [
            'Transcrieri automate',
            'Suport email',
            'Rapoarte de bază',
        ],
    ],
    'professional' => [
        'name' => 'Profesional',
        'price_monthly' => 299,
        'price_yearly' => 239,
        'minutes' => 2000,
        'bots' => 25,
        'channels' => 999,
        'max_products' => 5000,
        'overage_per_minute' => 0.10,
        'allowed_channels' => ['voice', 'whatsapp', 'facebook_messenger', 'instagram_dm', 'web_chatbot'],
        'features' => [
            'Toate 5 canalele',
            'Bază de cunoștințe partajată între canale',
            'Analiză de sentiment',
            'Suport prioritar 24/7',
            'Integrări CRM',
            'Dashboard avansat',
            'API access',
        ],
    ],
    'enterprise' => [
        'name' => 'Enterprise',
        'price_monthly' => 0,
        'price_yearly' => 0,
        'minutes' => 999999,
        'bots' => 999,
        'channels' => 999,
        'max_products' => 50000,
        'overage_per_minute' => 0,
        'allowed_channels' => ['voice', 'whatsapp', 'facebook_messenger', 'instagram_dm', 'web_chatbot'],
        'features' => [
            'Minute nelimitate',
            'Toate canalele + integrări custom',
            'SLA 99.99%',
            'Manager dedicat',
            'Onboarding personalizat',
            'Hosting dedicat',
            'Suport telefonic 24/7',
        ],
    ],
];
